[[clusters]]
    name = "test-dns-resolver"
    listen_addr = "0.0.0.0:6379"
    cache_type = "redis"
    listen_proto = "tcp"
    servers=[
        "localhost:6379",
    ]
    tcp_keepalive_secs = 0
    redis_ping_interval_secs = 0

[[clusters]]
    name = "test-mc-standalone"
    listen_addr = "0.0.0.0:7789"
    hash_tag = "{}"
    thread = 1
    cache_type = "memcache"
    servers = [
        "127.0.0.1:11211:10 mc-1",
    ]
    tcp_keepalive_secs = 0
    redis_ping_interval_secs = 0

    fetch_interval = 3600000 
    read_from_slave = false

    ping_fail_limit = 6 # 3 times
    ping_succ_interval = 1000 # 1 second
    ping_interval = 5000 # 5 seconds

    read_timeout = 1000
    write_timeout = 1000
    dial_timeout = 500
    listen_proto = "tcp"
    node_connections = 1

[[clusters]]
    name = "test-redis-standalone"
    listen_addr = "0.0.0.0:7787"
    hash_tag = "{}"
    cache_type = "redis"
    servers = [
        "127.0.0.1:6379:10 redis-1",
    ]
    tcp_keepalive_secs = 0
    redis_ping_interval_secs = 0
    redis_auth = "my-password"
    thread = 1
    fetch_interval = 3600000 
    read_from_slave = false

    ping_fail_limit = 10
    ping_interval = 30000

    read_timeout = 1000
    write_timeout = 1000
    dial_timeout = 500
    listen_proto = "tcp"
    node_connections = 1

[[clusters]]
    name = "test-cluster"
    listen_addr = "0.0.0.0:7788"
    hash_tag = "{}"
    thread = 1
    cache_type = "redis_cluster"
    servers = ["127.0.0.1:3300"]
    tcp_keepalive_secs = 0
    redis_ping_interval_secs = 0

    fetch_interval = 1800000 # 1800s , 30 minutes
    fetch_since_latest_cmd = 1000 # 3600s , 1 hour
    read_from_slave = false

    ping_fail_limit = 10
    ping_interval = 300

    read_timeout = 1000
    write_timeout = 1000
    dial_timeout = 500
    listen_proto = "tcp"
    node_connections = 1
